FROM openjdk:18-jdk-alpine
WORKDIR /app
COPY target/classes/ /app/
COPY bcprov-jdk18on-1.78.1.jar /app/
EXPOSE 7000
# Menjalankan server
CMD ["java", "-cp", ".:bcprov-jdk18on-1.78.1.jar", "ECDH.Server"]
