FROM openjdk:18-jdk-alpine
WORKDIR /app
COPY target/classes/ /app/
COPY bcprov-jdk18on-1.78.1.jar /app/
EXPOSE 5001
# Menjalankan server
CMD ["java", "-cp", ".:bcprov-jdk18on-1.78.1.jar", "ECC.Server"]
